export const CHAT_SET_PEOPLE_PROFILES = "CHAT_SET_PEOPLE_PROFILES";
export const CHAT_ADD_PEOPLE_PROFILES = "CHAT_ADD_PEOPLE_PROFILES";
export const CLEAR_CHAT_STATE = "CLEAR_CHAT_STATE";

export const SET_CHAT_DATA = "SET_CHAT_DATA";
