export const HOME_SET_TAB = "HOME_SET_TAB";
export const HOME_SET_MY_ALL_GROUP = "HOME_SET_MY_ALL_GROUP";
export const HOME_SET_ALL_GROUP = "HOME_SET_ALL_GROUP";
export const HOME_SET_GROUP_DETAIL = "HOME_SET_GROUP_DETAIL";
